spring.application.name=EasyBus
server.port=9091
spring.datasource.url=jdbc:mysql://68.178.148.82:3306/easy_bus
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=easybus_admin
spring.datasource.password=EasyBusAdmin@123
spring.jpa.hibernate.ddl-auto=update